### ISSUE TITLE
[Feature Request] Enable Battery Saver on tap on the tile in QS

### ISSUE THREAD

**Issue by Wrx95Pro** [Solarphlare/BatteryTile#2]
I like your app and use it every day, but it lacks one thing that was in older Android releases - ability to enable or disable Battery Saver. 
As I know, some applications for creation custom QS tiles allow this behavior by giving the app special permission via ADB, named "android.permission.WRITE_SECURE_SETTINGS"
So, if you could make this real, I'll be very happy and pleased ❤️

**Comment by Solarphlare** [comment]
I did actually have a build of the app that attempted to mimic the Battery Saver tile, but since I didn't know that you could manually grant the secure settings permission, I thought that toggling Battery Saver wouldn't have been possible. Thanks for letting me know about the ADB workaround—I'll get this added in as soon as I can.

**Comment by Solarphlare** [comment]
This has been added in [v1.3.0](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.3.0).

**Comment by Wrx95Pro** [comment]
❤️❤️❤️ thx
